module.exports = {
    en: {
        translation: {
            WELCOME_MSG: 'Search More Health welcomes you, we are at your service, are you looking for any kind of information?',
            REGISTER_MSG: 'I see you need information regarding %ss disease, ',
            SAY_MSG: '',
            GREET_MSG: '',
            MISSING_MSG: 'Looks like you still havent told me what type of disease you have or what you need information about. Try saying, "I have another disease." ',
            OVERWRITE_MSG: 'If you want to change the disease type just say, "I have another disease".',
            HELP_MSG: 'You can ask me if you want a clinic recommendation, just by saying "recommend a clinic". ',
            GOODBYE_MSG: 'See you later! ',
            REFLECTOR_MSG: 'You just activated %s ',
            FALLBACK_MSG: 'Sorry, I dont know anything about that. Please try again. ',
            ERROR_MSG: 'Sorry, there was a problem. Please try again. ',
            RECOMEN_MSG: 'The clinic that we recommend for the disease you administered, which is %s',
            LOCALIZATION_MSG:'The location of the clinic shown is the following, %s',
            CATALOGO_MSG: 'in case you require information on another disease, here we show you the variety of diseases that you can request information on.',
            DESPEDIDA_MSG : 'See you soon!',
            DESPEDIDA2_MSG: 'We wish you a good day!',
            
            FALLBACKPRIMARY_MSG:'Were Sorry',
            FALLBACKSECONDARY_MSG:'I dont understand the action you want to perform',
            FALLBACKHIND_MSG:'Please try again',
            
            ERRORPRIMARY_MSG:'WOW!',
            ERRORSECONDARY_MSG:'An error has occurred',
            ERRORHIND_MSG:'Please try again',
            
            ARTRITIS_IMG: 'https://www.sanatorio-americano.com.ar/assets/novedades/nov_artritis_reumatoide2505.jpg',
            ARTRITIS_MSG_primaryText: 'Arthritis',
            ARTRITIS_MSG_locationText: 'Arthritis is an inflammation of the joints that causes pain and even deformities.',
            ARTRITIS_MSG_secondaryText: 'The recommendation is that you look for a specialist within a clinic for your treatment, in addition to not taking the affected areas to their limits',
            
            DIABETES_IMG: 'https://www.topdoctors.mx/files/Image/large/f0245962b7cd125ebbc6445879251a37.jpg',
            DIABETES_MSG_primaryText: 'Diabetes',
            DIABETES_MSG_locationText: 'Diabetes is a chronic metabolic disease characterized by elevated blood glucose (or blood sugar) levels',
            DIABETES_MSG_secondaryText: 'Talk to your healthcare provider to see if there is anything else you can do to delay or prevent diabetes, limit foods with excess sugar',
            
            COLESTEROL_IMG: 'https://cesida.org/wp-content/uploads/2016/02/colesterol.png',
            COLESTEROL_MSG_primaryText: 'Cholesterol',
            COLESTEROL_MSG_locationText: 'The most common cause of cholesterol is from leading a very unhealthy life derived from a poor diet',
            COLESTEROL_MSG_secondaryText: 'The recommendation is that you go to an expert on the subject of cholesterol, who will give you methods so that you can eat better and get good habits',
            
            HIPERTENSION_IMG: 'https://vincentilab.com/wp-content/uploads/2021/05/VI_arteria_animada.gif',
            HIPERTENSION_MSG_primaryText: 'Hypertension',
            HIPERTENSION_MSG_locationText: 'We speak of hypertension when the blood pressure in our blood vessels is too high, 40/190 mmHg',
            HIPERTENSION_MSG_secondaryText: 'To help control your blood pressure, you should limit the amount of sodium (salt) you eat and increase the amount of potassium in your diet. It is also important to eat foods that are low in fat as well as lots of fruits, vegetables',
            
            INSUFICIENCIA_IMG: 'https://sandbox.cuidandotucorazon.com/wp-content/uploads/2019/07/latido-normal-insuficiencia.gif',
            INSUFICIENCIA_MSG_primaryText: 'Heart Failure',
            INSUFICIENCIA_MSG_locationText: 'A condition in which the heart can no longer pump oxygen-rich blood to the rest of the body efficiently.',
            INSUFICIENCIA_MSG_secondaryText: 'Follow a Mediterranean diet, without salt and low in fat, Avoid drinking alcoholic beverages and we recommend you stop smoking, Control the amount of fluids you drink, Exercise regularly, according to your doctor',
            
            VITE_TITLE: 'Clinica Vite',
            VITE_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/ClinicaVite.jpeg',
            VITE_LOCATION_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/mapVite.png',
            VITE_MSG_primaryText: 'Clinica Marcelo Vite Flores',
            VITE_MSG_locationText: 'Colonia Capitan antonio reyes, calle cuauhtemoc no 16',
            VITE_MSG_secondaryText: 'Open from 8:00 AM - 22:00hrs <br /><br />',
            VITE_BUTTON1: 'Call',
            VITE_BUTTON2: '¿How to get there?',
            
            BETANIA_TITLE: 'Clinica Betania',
            BETANIA_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/clinicaBetania.jpeg',
            BETANIA_LOCATION_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/mapBetania.png',
            BETANIA_MSG_primaryText: 'Clinica Betania',
            BETANIA_MSG_locationText: 'Le atiende el Dr. Jorge Toxtle Roman, Colonia Tahuizan, Calle Allende, Frente a la pasteleria Pier',
            BETANIA_MSG_secondaryText: 'Open from 8:00 hrs - 14:00 hrs / 16:00 hrs a 20:00 hrs<br /> ',
            BETANIA_BUTTON1: 'Call',
            BETANIA_BUTTON2: '¿How to get there?',
            
            CLIHUEJUTLA_TITLE: 'Clinica Huejutla',
            CLIHUEJUTLA_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/ClinicaHuejutla.jpg',
            CLIHUEJUTLA_LOCATION_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/mapCliHuejutla.png',
            CLIHUEJUTLA_MSG_primaryText: 'CLINICA HUEJUTLA',
            CLIHUEJUTLA_MSG_locationText: '11-B Calle Prof. Juan Mojica<br />Huejutla, HGO<br />(785) 387-0290',
            CLIHUEJUTLA_MSG_secondaryText: 'Open from 8:00 AM - 10:00 PM<br />   <br />',
            CLIHUEJUTLA_BUTTON1: 'Call',
            CLIHUEJUTLA_BUTTON2: '¿How to get there?',
            
            CIGO_TITLE: 'Clinica CIGO',
            CIGO_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/ClinicaCigo.png',
            CIGO_LOCATION_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/mapCigo.png',
            CIGO_MSG_primaryText: 'Clinica CIGO',
            CIGO_locationText: 'C. Cuauhtémoc 17, Capitán Antonio Reyes, 43000 Huejutla, Hgo.',
            CIGO_MSG_secondaryText: 'Open from 9:00 AM - 4:00 PM<br />789 896 1483',
            CIGO_BUTTON1: 'Call',
            CIGO_BUTTON2: '¿How to get there?',
            
            MEDICA21_TITLE: 'Clinica Medica21',
            MEDICA21_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/ClinicaMedica21.jpg',
            MEDICA21_LOCATION_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/mapMedica.png',
            MEDICA21_MSG_primaryText: 'Clinica Medica 21',
            MEDICA21_locationText: '57 Juarez Centro<br />Huejutla, HGO<br />(253) 387-0290',
            MEDICA21_MSG_secondaryText: 'Open from 9:00 AM - 4:00 PM<br /><br />',
            MEDICA21_BUTTON1: 'Call',
            MEDICA21_BUTTON2: '¿How to get there?',
        }
    },
    es: {
        translation: {
            WELCOME_MSG: 'Search More Health te da la bienvenida, estamos a sus ordenes, busca algun tipo de informacion?',
            REGISTER_MSG: 'Veo que necesitas informacion respecto a la enfermedad de %s, ',
            SAY_MSG: '',
            GREET_MSG: '',
            MISSING_MSG: 'Parece que aun no me has dicho el tipo de enfermedad que padeces o que requieres informacion. Prueba decir, "padezco de otra enfermedad". ',
            OVERWRITE_MSG: 'Si quieres cambiar el tipo de enfermedad solo di , "padezco de otra enfermedad".',
            HELP_MSG: 'Puedes preguntarme si quieres alguna recomendacion de alguna clinica o informacion de alguna enfermedad, solo diciendo "recomiendame una clinica" o "padezco de diabetes". ',
            GOODBYE_MSG: 'Hasta luego! ',
            REFLECTOR_MSG: 'Acabas de activar %s ',
            FALLBACK_MSG: 'Lo siento, no se nada sobre eso. Por favor inténtalo otra vez. ',
            ERROR_MSG: 'Lo siento, ha habido un problema. Por favor inténtalo otra vez. ',
            RECOMEN_MSG: 'La clinica que te recomendamos por la enfermedad que administrastes el cual es %s',
            LOCALIZATION_MSG:'La localizacion de la clinica mostrada es la siguiente, %s',
            CATALOGO_MSG: 'en caso de requerir informacion de otra enfermedad, aqui te mostramos la variedad de enfermedades que puedes solicitar informacion.',
            DESPEDIDA_MSG: '¡Hasta pronto!',
            DESPEDIDA2_MSG: 'Le deseamos un buen día!',
            
            FALLBACKPRIMARY_MSG:'Lo Lamentamos',
            FALLBACKSECONDARY_MSG:'No entiendo la accion que quieres realizar',
            FALLBACKHIND_MSG:'Por favor intentalo de nuevo',
            
            ERRORPRIMARY_MSG:'¡Oh vaya!',
            ERRORSECONDARY_MSG:'Ha ocurrido un error',
            ERRORHIND_MSG:'Por favor intentalo de nuevo',
            
            ARTRITIS_IMG: 'https://www.sanatorio-americano.com.ar/assets/novedades/nov_artritis_reumatoide2505.jpg',
            ARTRITIS_MSG_primaryText: 'Artritis',
            ARTRITIS_MSG_locationText: 'La artritis consta en una inflamacion de las articulaciones que causa dolor e incluso deformaciones.',
            ARTRITIS_MSG_secondaryText: 'La recomendacion es que busque un especialista dentro de una clinica para su tratamiento, ademas de no llevar a sus limites las areas afectadas',
            
            DIABETES_IMG: 'https://www.topdoctors.mx/files/Image/large/f0245962b7cd125ebbc6445879251a37.jpg',
            DIABETES_MSG_primaryText: 'Diabetes',
            DIABETES_MSG_locationText: 'La diabetes es una enfermedad metabólica crónica caracterizada por niveles elevados de glucosa en sangre (o azúcar en sangre)',
            DIABETES_MSG_secondaryText: 'Hable con su proveedor de atención médica para ver si hay algo más que pueda hacer para retrasar o prevenir la diabetes, limite las comidas con exceso de azucar',
            
            COLESTEROL_IMG: 'https://cesida.org/wp-content/uploads/2016/02/colesterol.png',
            COLESTEROL_MSG_primaryText: 'Colesterol',
            COLESTEROL_MSG_locationText: 'La causa mas comun del colesterol es por llevar una vida muy poco saludable derivado de una mala alimentacion',
            COLESTEROL_MSG_secondaryText: 'La recomendacion es que acuda con un experto en el tema del colesterol, el cual le de metodos para que pueda alimentarse mejor y hacerse de buenos habitos',
            
            HIPERTENSION_IMG: 'https://vincentilab.com/wp-content/uploads/2021/05/VI_arteria_animada.gif',
            HIPERTENSION_MSG_primaryText: 'Hipertension',
            HIPERTENSION_MSG_locationText: 'Se habla de hipertensión cuando la presión de la sangre en nuestros vasos sanguíneos es demasiado alta de 40/190 mmHg',
            HIPERTENSION_MSG_secondaryText: 'Para ayudar a controlar su presión arterial, debe limitar la cantidad de sodio (sal) que come y aumentar la cantidad de potasio en su dieta. También es importante comer alimentos que sean bajos en grasa así como muchas frutas, verduras',
            
            INSUFICIENCIA_IMG: 'https://sandbox.cuidandotucorazon.com/wp-content/uploads/2019/07/latido-normal-insuficiencia.gif',
            INSUFICIENCIA_MSG_primaryText: 'Insuficiencia Cardiaca',
            INSUFICIENCIA_MSG_locationText: 'Es una afección en la cual el corazón ya no puede bombear sangre rica en oxígeno al resto del cuerpo de forma eficiente.',
            INSUFICIENCIA_MSG_secondaryText: 'Siga una dieta mediterránea, sin sal y baja en grasas, Evite la ingesta de bebidas alcohólicas y recomendamos deje de fumar, Controle la cantidad de líquidos que toma Realice ejercicio físico de forma regular, acorde a su medico',
            
            VITE_TITLE: 'Clinica Vite',
            VITE_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/ClinicaVite.jpeg',
            VITE_LOCATION_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/mapVite.png',
            VITE_MSG_primaryText: 'Clinica Marcelo Vite Flores',
            VITE_MSG_locationText: 'Colonia Capitan antonio reyes, calle cuauhtemoc no 16',
            VITE_MSG_secondaryText: 'Abierto 8:00 AM - 22:00hrs <br /><br />',
            VITE_BUTTON1: 'Llamar',
            VITE_BUTTON2: '¿Como llegar?',
            
            BETANIA_TITLE: 'Clinica Betania',
            BETANIA_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/clinicaBetania.jpeg',
            BETANIA_LOCATION_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/mapBetania.png',
            BETANIA_MSG_primaryText: 'Clinica Betania',
            BETANIA_MSG_locationText: 'Le atiende el Dr. Jorge Toxtle Roman',
            BETANIA_MSG_secondaryText: 'Abierto 8:00 hrs - 14:00 hrs / 16:00 hrs a 20:00 hrs<br /> Colonia Tahuizan, Calle Allende, Frente a la pasteleria Pier',
            BETANIA_BUTTON1: 'Llamar',
            BETANIA_BUTTON2: '¿Como llegar?',
            
            CLIHUEJUTLA_TITLE: 'Clinica Huejutla',
            CLIHUEJUTLA_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/ClinicaHuejutla.jpg',
            CLIHUEJUTLA_LOCATION_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/mapCliHuejutla.png',
            CLIHUEJUTLA_MSG_primaryText: 'CLINICA HUEJUTLA',
            CLIHUEJUTLA_MSG_locationText: '11-B Calle Prof. Juan Mojica<br />Huejutla, HGO<br />(785) 387-0290',
            CLIHUEJUTLA_MSG_secondaryText: '8:00 AM - 10:00 PM<br />   <br />',
            CLIHUEJUTLA_BUTTON1: 'Llamar',
            CLIHUEJUTLA_BUTTON2: '¿Como llegar?',
            
            CIGO_TITLE: 'Clinica CIGO',
            CIGO_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/ClinicaCigo.png',
            CIGO_LOCATION_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/mapCigo.png',
            CIGO_MSG_primaryText: 'Clinica CIGO',
            CIGO_locationText: 'C. Cuauhtémoc 17, Capitán Antonio Reyes, 43000 Huejutla, Hgo.',
            CIGO_MSG_secondaryText: 'ABIERTO DE 9:00 AM - 4:00 PM<br />789 896 1483',
            CIGO_BUTTON1: 'Llamar',
            CIGO_BUTTON2: '¿Como llegar?',
            
            MEDICA21_TITLE: 'Clinica Medica21',
            MEDICA21_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/ClinicaMedica21.jpg',
            MEDICA21_LOCATION_IMG: 'https://raw.githubusercontent.com/OswaldoYair/ProyectoAlexaSkill/main/Clinicas/mapMedica.png',
            MEDICA21_MSG_primaryText: 'Clinica Medica 21',
            MEDICA21_locationText: '57 Juarez Centro<br />Huejutla, HGO<br />(253) 387-0290',
            MEDICA21_MSG_secondaryText: 'Abierto de 9:00 AM - 4:00 PM<br /><br />',
            MEDICA21_BUTTON1: 'Llamar',
            MEDICA21_BUTTON2: '¿Como llegar?',
            
        }
    }
}